services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=employees'
      - 'POSTGRES_PASSWORD=Poria1382'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
